AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SendPaymentOrdersLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: otp-lambdas
        S3Key: enviar-ordem-pagamento.zip
      FunctionName: enviar-ordem-pagamento
      Handler: index.handler
      Role: !GetAtt SendPaymentOrdersRole.Arn
      Runtime: nodejs14.x
      Environment:
        Variables:
          processOrdersQueueUrl: !Sub 'https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/ordens-processadas'
          generatedOrdersQueueUrl: !Sub 'https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/ordens-geradas'
  SendPaymentOrdersRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: 'SendPaymentOrdersPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:SendMessage'
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                Resource:
                  - !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:ordens-geradas' # Substitua pelo URL da sua fila de origem
                  - !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:ordens-processadas' # Substitua pelo URL da sua fila de destino
  ProcessQueueEvent:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:ordens-geradas'
      FunctionName: !Ref SendPaymentOrdersLambda