AWSTemplateFormatVersion: "2010-09-09"
Resources:
  GeradorOrdemPagamentoFunctionLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: gerador-ordem-pagamento-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: sns-publish
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:OrdensGeradasTopic"
  GeradorOrdemPagamentoFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: otp-lambdas
        S3Key: gerador-ordem-pagamento.zip
      FunctionName: gerar-ordens-pagamento
      Handler: index.handler
      Role: !GetAtt GeradorOrdemPagamentoFunctionLambdaExecutionRole.Arn
      Runtime: nodejs14.x
  ApiGatewayRestApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "GeradorOrdemPagamentoAPI"
  ApiGatewayResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: "ordem-pagamento"
  ApiGatewayMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResource
      HttpMethod: "POST"
      AuthorizationType: "NONE"
      Integration:
        Type: "AWS_PROXY"
        IntegrationHttpMethod: "POST"
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GeradorOrdemPagamentoFunction.Arn}/invocations"
        PassthroughBehavior: "WHEN_NO_MATCH"
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
  GeradorOrdemPagamentoFunctionLambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt GeradorOrdemPagamentoFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/*/ordem-pagamento"
Outputs:
  ApiGatewayRestApiId:
    Value: !Ref ApiGatewayRestApi
  ApiGatewayEndpointUrl:
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/ordem-pagamento"
